Conan recipefile
elear-solutions/catta pull request #3
Opened 2019-07-30 07:37 UTC by amiya-elear

2019-07-31 19:02 UTC, deekshith-elear approved these changes

2019-08-01 07:30 UTC, varun-elear requested changes

2019-08-01 07:30 UTC, varun-elear commented on conanfile.py
> +    description = "This recipe file used to build and package binaries of cocostandard repository"
`catta` instead of `cocostandard`

2019-08-01 07:57 UTC, amiya-elear commented on conanfile.py
> +    description = "This recipe file used to build and package binaries of cocostandard repository"
handled

2019-08-01 11:18 UTC, varun-elear approved these changes

2019-08-01 12:24 UTC, merged